<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $reportName }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
            color: #111111;
            margin: 24px 32px 64px 32px;
        }

        .header {
            border-bottom: 1px solid #111111;
            padding-bottom: 8px;
            margin-bottom: 16px;
        }

        .company-name {
            font-size: 14px;
            font-weight: bold;
        }

        .report-name {
            font-size: 20px;
            margin: 4px 0;
        }

        .generated-at {
            font-size: 11px;
        }

        .section-title {
            font-size: 14px;
            margin: 16px 0 8px 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th, td {
            border: 1px solid #cccccc;
            padding: 6px 8px;
            text-align: left;
        }

        th {
            width: 40%;
        }

        .footer {
            position: fixed;
            bottom: -48px;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 10px;
            color: #555555;
        }

        .footer .page-number:after {
            content: counter(page);
        }
    </style>
</head>
<body>
    <footer class="footer">
        Page <span class="page-number"></span> &mdash; Generated by Fayadhowr ERP
    </footer>

    <header class="header">
        <div class="company-name">{{ $companyName }}</div>
        <div class="report-name">{{ $reportName }}</div>
        <div class="generated-at">Generated At: {{ $generatedAt }}</div>
    </header>

    <section>
        <div class="section-title">Filter Information</div>
        <table>
            <tr>
                <th>Filter</th>
                <td>{{ $filter }}</td>
            </tr>
            <tr>
                <th>Start Date</th>
                <td>{{ $startDate ?? 'N/A' }}</td>
            </tr>
            <tr>
                <th>End Date</th>
                <td>{{ $endDate ?? 'N/A' }}</td>
            </tr>
        </table>
    </section>

    <section>
        <div class="section-title">Report Data</div>
        <table>
            @foreach ($metrics as $label => $value)
                <tr>
                    <th>{{ $label }}</th>
                    <td>{{ $value }}</td>
                </tr>
            @endforeach
        </table>
    </section>
</body>
</html>
